# Generated by Django 5.2.4 on 2025-07-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catergory",
            new_name="Category",
        ),
    ]
