# Generated by Django 5.2.4 on 2025-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0005_rename_catergory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
